# Generated by Django 5.1.3 on 2024-12-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PypiLibraries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя библиотеки')),
                ('path', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Путь к файлам')),
                ('description', models.TextField(blank=True, help_text='Краткое описание библиотеки или её предназначение', verbose_name='Описание')),
                ('documentation', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на документацию')),
            ],
        ),
    ]
