# Generated by Django 5.1.3 on 2025-01-27 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название лабораторной работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('open_time', models.DateTimeField(verbose_name='Время открытия')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('is_open', models.BooleanField(default=True, verbose_name='Открыта')),
                ('allowed_groups', models.ManyToManyField(related_name='allowed_lab_works', to='application.group', verbose_name='Доступные группы')),
            ],
        ),
        migrations.CreateModel(
            name='LabWorkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_open', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')),
                ('date_answer', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('open_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при открытии')),
                ('load_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при загрузке')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Текстовый ответ')),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='lab_work/files', verbose_name='Файловый ответ')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('lab_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labwork.labwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_work_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
