# Generated by Django 5.1.3 on 2025-01-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labworkresult',
            name='file_answer',
        ),
        migrations.CreateModel(
            name='LabWorkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lab_work/files', verbose_name='Файл')),
                ('lab_work_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='labwork.labworkresult')),
            ],
        ),
    ]
