# Generated by Django 5.1.3 on 2025-01-27 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labwork', '0002_remove_labworkresult_file_answer_labworkfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabWorkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lab_work/attachments/', verbose_name='Прикрепленный файл')),
                ('lab_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='labwork.labwork', verbose_name='Лабораторная работа')),
            ],
        ),
    ]
