# Generated by Django 5.1.3 on 2024-11-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/task/files', verbose_name='Answer task')),
                ('date_answer', models.CharField(default='28.11.2024', max_length=100)),
                ('time_answer', models.CharField(default='13:59', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_group', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512)),
                ('hash_value', models.CharField(max_length=65)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=100, verbose_name='ФИО студента')),
                ('user_login', models.CharField(max_length=100, verbose_name='username')),
                ('user_hash_value', models.CharField(db_index=True, max_length=65)),
                ('user_password', models.CharField(max_length=32)),
                ('user_telegram_username', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.answertask')),
            ],
        ),
        migrations.AddField(
            model_name='answertask',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='application.students'),
        ),
        migrations.AddField(
            model_name='students',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='application.studentsgroups'),
        ),
        migrations.CreateModel(
            name='StudentsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studnet_image', models.ImageField(upload_to='media/students')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='application.students')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_ip', models.CharField(max_length=16)),
                ('tag_date', models.CharField(default='28.11.2024', max_length=100)),
                ('tag_time', models.CharField(default='13:59', max_length=100)),
                ('tag_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='application.students')),
            ],
        ),
        migrations.CreateModel(
            name='TaskImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/tasks/images')),
                ('max_rate', models.IntegerField()),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='application.tasktable')),
            ],
        ),
        migrations.CreateModel(
            name='RateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='application.tasktable')),
            ],
        ),
        migrations.AddField(
            model_name='answertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='application.tasktable'),
        ),
        migrations.CreateModel(
            name='TeacherGroupControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_ctrl', to='application.studentsgroups')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_field', to='application.teachermodel')),
            ],
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='application.usermodel'),
        ),
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='application.usermodel'),
        ),
    ]
