# Generated by Django 5.1.3 on 2024-11-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskimages',
            name='max_rate',
        ),
        migrations.AddField(
            model_name='tasktable',
            name='max_rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answertask',
            name='time_answer',
            field=models.CharField(default='14:28', max_length=100),
        ),
        migrations.AlterField(
            model_name='studenttag',
            name='tag_time',
            field=models.CharField(default='14:28', max_length=100),
        ),
    ]
