# Generated by Django 5.1.3 on 2024-11-28 18:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_taskimages_max_rate_tasktable_max_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hash_value', models.CharField(max_length=65, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('max_rate', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='replyanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='ratetask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_group',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studenttag',
            name='tag_student',
        ),
        migrations.RemoveField(
            model_name='studentsimage',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teachergroupcontrol',
            name='control',
        ),
        migrations.RemoveField(
            model_name='taskimages',
            name='taskid',
        ),
        migrations.RemoveField(
            model_name='teachergroupcontrol',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_telegram_username',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='application.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='application.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_status', models.CharField(blank=True, max_length=50, null=True)),
                ('lunch_status', models.CharField(blank=True, max_length=50, null=True)),
                ('morning_time', models.TimeField(blank=True, null=True)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('lateness', models.CharField(blank=True, default='', max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='application.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='application.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='application.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/task/files')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='application.studentprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='application.task')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='application.usermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='AnswerTask',
        ),
        migrations.DeleteModel(
            name='ReplyAnswer',
        ),
        migrations.DeleteModel(
            name='RateTask',
        ),
        migrations.DeleteModel(
            name='StudentTag',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='StudentsImage',
        ),
        migrations.DeleteModel(
            name='StudentsGroups',
        ),
        migrations.DeleteModel(
            name='TaskImages',
        ),
        migrations.DeleteModel(
            name='TaskTable',
        ),
        migrations.DeleteModel(
            name='TeacherGroupControl',
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
    ]
